### ISSUE TITLE
Ignore Escaping in serialization

### ISSUE THREAD

**Issue by tf-thomas-hofbauer** [SAP/abap-to-json#11]
Hi Alexey.

Recently there was a request where a windows path name was used in an variable.
The path was escaped by the serializer with additional backslashes. 
Normally I would prefer to use escaped values but in this case the reciever could not deal with it.
Is there a possiblity to deactivate escaping in serialization case?

br
Thomas Hofbauer

**Comment by alexey-arseniev** [comment]
Hi Thomas,

unfortunately - no. Escaping of special characters ensures the output of the valid JSON. If this step is skipped you may get unescaped '"' or '\' that will lead to errors during JSON parsing on another side. It is very critical, that is why there is no such option. In your case imagine ('"' is not an issue normally), that path contains "C:\new". If it does not escape you get "C: <new line> new" on unescape. 

In addition to that, I use now built-in ABAP escape function that I can not control. E.g. it escapes for valid JSON or nothing.

IMHO: your receiver shall do a proper processing. 

Workarounds you may do can be:

- post-processing of the JSON before sending it using regular expressions (will not be easy).
- redefining dump_int method and doing special handling for attributes where you have paths. 

BR, Alexey.

**Comment by tf-thomas-hofbauer** [comment]
Hi Alexey.

Those are exactly my thoughts when we developed it.
Sadly it's not an option so we went with the Regex Postprocessing afterwards.
Thanks for you time.

br
Thomas
