### ISSUE TITLE
endless loop in lcl_util=>read_string at deserializing a invalid json string

### ISSUE THREAD

**Issue by tf-Lukas-Klausner** [SAP/abap-to-json#7]
Hi,

following statement ends in an endless loop in the lasted version (19):
`z_ui2_json=>generate( '{"error":"n \"<\"\">' ).`
Problem is in Method lcl_util=>read_string.
In version 16 this bug was not present.

BR
Lukas

**Comment by alexey-arseniev** [comment]
Hi Lukas,

Thanks! Yes, it was a new bug. Fixed it just now. You may retest with the newest code.
https://github.com/SAP/abap-to-json/commit/b2b25e9920159ba42ed059d23f31b22d7b2a3c23 

BR, Alexey

**Comment by tf-Lukas-Klausner** [comment]
Hi Alexey,
Thanks for the quick bugfix.
My retest was successful.
BR, Lukas
